### ISSUE TITLE
TypeError: sampled_loss() got an unexpected keyword argument 'logits

### ISSUE THREAD

**Issue by loretoparisi** [cmusphinx/g2p-seq2seq#104]
I can train and load inference from the CMUDict model with TensorFlow 1.5 (and I supposed TF 1.6 as well it will work - thanks for your help 💯 ). 
Now I'm trying to train from scratch a new model, based on a variant of the CMU dictionary, where I have added a different symbol set as the second column and kept the same entries in the first column, but I get an error:

```
  File "/usr/local/bin/g2p-seq2seq", line 11, in <module>
    load_entry_point('g2p-seq2seq==5.0.0a0', 'console_scripts', 'g2p-seq2seq')()
  File "build/bdist.linux-x86_64/egg/g2p_seq2seq/app.py", line 83, in main
  File "build/bdist.linux-x86_64/egg/g2p_seq2seq/g2p.py", line 144, in prepare_data
  File "build/bdist.linux-x86_64/egg/g2p_seq2seq/data_utils.py", line 250, in prepare_g2p_data
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: 'data/models/cmudict-test/'
Preparing G2P data
Creating vocabulary data/models/cmudict-test/vocab.phoneme
Creating vocabulary data/models/cmudict-test/vocab.grapheme
Reading development and training data.
Creating model with parameters:
Learning rate:        0.5
LR decay factor:      0.99
Max gradient norm:    5.0
Batch size:           64
Size of layer:        64
Number of layers:     2
Steps per checkpoint: 200
Max steps:            0
Optimizer:            sgd
Mode:                 g2p

Traceback (most recent call last):
  File "/usr/local/bin/g2p-seq2seq", line 11, in <module>
    load_entry_point('g2p-seq2seq==5.0.0a0', 'console_scripts', 'g2p-seq2seq')()
  File "build/bdist.linux-x86_64/egg/g2p_seq2seq/app.py", line 87, in main
  File "build/bdist.linux-x86_64/egg/g2p_seq2seq/g2p.py", line 218, in create_train_model
  File "build/bdist.linux-x86_64/egg/g2p_seq2seq/g2p.py", line 179, in __prepare_model
  File "build/bdist.linux-x86_64/egg/g2p_seq2seq/seq2seq_model.py", line 177, in __init__
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/legacy_seq2seq/python/ops/seq2seq.py", line 1224, in model_with_buckets
    softmax_loss_function=softmax_loss_function))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/legacy_seq2seq/python/ops/seq2seq.py", line 1137, in sequence_loss
    softmax_loss_function=softmax_loss_function))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/legacy_seq2seq/python/ops/seq2seq.py", line 1092, in sequence_loss_by_example
    crossent = softmax_loss_function(labels=target, logits=logit)
TypeError: sampled_loss() got an unexpected keyword argument 'logits'
```

The input file has the same format of the `cmudict/cmudict.dict` file, and I can see that in the output folder three files has been created before the error:

```
# ls -l data/models/cmudict-test/
total 1264
-rw-r--r-- 1 root root      20 Mar 27 09:37 model.params
-rw-r--r-- 1 root root     103 Mar 27 09:37 vocab.grapheme
-rw-r--r-- 1 root root 1285528 Mar 27 09:37 vocab.phoneme
```

**Comment by loretoparisi** [comment]
**[UPDATE]**
This error seems to be related to https://github.com/tensorflow/models/issues/1736

**Comment by loretoparisi** [comment]
@nurtas-m A wonder: since the training it is working with `TF 1.5` and the provided `cmudict` example, it is possible that this is due to the dictionary format (for some reason)?
I have just realized that while in the cmudict I have got white space separated symbols for the CMU Alphabet like:

```
'bout B AW1 T
'cause K AH0 Z
'course K AO1 R S
'cuse K Y UW1 Z
'em AH0 M
'frisco F R IH1 S K OW0
'gain G EH1 N
'kay K EY1
'm AH0 M
'n AH0 N
```

in my dictionary the ipa symbols are not separated in the same way

```
a ʌ
a(1) ejˈ
a's ejˈz
a. ejˈ
a.'s ejˈz
a.s ejˈz
aaa tɹɪˌpʌlejˈ
aaberg ɑˈbɚg
aachen ɑˈkʌn
```

Of course, I'm not sure if this could be the issue.

**Comment by nurtas-m** [comment]
Yes, you are absolutely right. In split_to_grapheme_phoneme() function in data_utils.py module, it is supposed that the phonemes in your input dictionary can be splitted by python's split() function. So, it is required white spaces between phonemes. Conversely, no white spaces needed between graphemes.

**Comment by loretoparisi** [comment]
@nurtas-m thank you! So I should find a way to split the IPA phonemes into chars. Any hint?

**Comment by nurtas-m** [comment]
Yes, you may just modify line 165 in data_utils.py module in order to satisfy your input dictionary format:
`phonemes.append(list(split_line[1]))`

**Comment by loretoparisi** [comment]
@nurtas-m hello, thanks I did some changes to support at least this parameter from `os.environment` so that one can eventually split phonemes. I have also added the `size` param from env so that you could do

```
root@dbb58814d105:~# export g2p_size=512
root@dbb58814d105:~# export g2p_split_phonemes=True
g2p-seq2seq --train data/dict/cmudict/cmudict.dict --model data/models/cmudict-512 2>&1 >> ./train.log &
```

You can check the changes here: https://github.com/loretoparisi/g2p-seq2seq/blob/master/g2p_seq2seq/app.py#L62

and in https://github.com/loretoparisi/g2p-seq2seq/blob/master/g2p_seq2seq/data_utils.py#L154

By the way, I was trying now the CMUDict-512, since using the CMU-IPA, I get the error anyways:

```
root@dbb58814d105:~#  g2p-seq2seq --train data/dict/cmudict-ipa/cmudict-ipa.dict --model data/models/cmudict-ipa/ 2>&1 >> ./train.log
Traceback (most recent call last):
  File "/usr/local/bin/g2p-seq2seq", line 11, in <module>
    load_entry_point('g2p-seq2seq==5.0.0a0', 'console_scripts', 'g2p-seq2seq')()
  File "build/bdist.linux-x86_64/egg/g2p_seq2seq/app.py", line 92, in main
  File "build/bdist.linux-x86_64/egg/g2p_seq2seq/g2p.py", line 218, in create_train_model
  File "build/bdist.linux-x86_64/egg/g2p_seq2seq/g2p.py", line 179, in __prepare_model
  File "build/bdist.linux-x86_64/egg/g2p_seq2seq/seq2seq_model.py", line 177, in __init__
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/legacy_seq2seq/python/ops/seq2seq.py", line 1224, in model_with_buckets
    softmax_loss_function=softmax_loss_function))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/legacy_seq2seq/python/ops/seq2seq.py", line 1137, in sequence_loss
    softmax_loss_function=softmax_loss_function))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/legacy_seq2seq/python/ops/seq2seq.py", line 1092, in sequence_loss_by_example
    crossent = softmax_loss_function(labels=target, logits=logit)
TypeError: sampled_loss() got an unexpected keyword argument 'logits'
```

**Comment by nurtas-m** [comment]
Ok, thank you very much for your contribution!
Can you, please, try to split phonemes with white-spaces in CMU-IPA dictionary before you feed it to the program? And check if all the lines have at least one grapheme and one phoneme. 
It seems, that because of parameters' order changes in tf.nn.sampled_softmax_loss() function (https://www.tensorflow.org/api_docs/python/tf/nn/sampled_softmax_loss), labels and inputs get mixed up. So, can you, please, add the names of parameters when you call tf.nn.sampled_softmax_loss() function in seq2seq_model.py module in a sampled_loss() function at the row 115:
tf.nn.sampled_softmax_loss(weights=local_w_t, biases=local_b,  inputs=local_inputs, labels=labels,
num_sampled=num_samples, num_classes=self.target_vocab_size)

**Comment by loretoparisi** [comment]
@nurtas-m thanks still investigating, at this time I have swtiched to *TF 1.6* and I was able to start training without the issue, so that seems to be the cause (that change in the method signature). Now I'm looking to the `IPA` dictionary phonemes list, since as far as I know, some symbols are made of two chars like `W'` so, the split expression should be (could be) simply a list of the IPA symbols.

**Comment by loretoparisi** [comment]
@nurtas-m so, you are right, I was wrong reading the `perplexity` indecision metrics. Also I think something happened while training the 512 layer size, since after it ended I can see

```
root@8932ca155955:~# echo "hello" | g2p-seq2seq --interactive --model data/models/cmudict/
Loading vocabularies from data/models/cmudict/
Creating 2 layers of 64 units.
Reading model parameters from data/models/cmudict/
> HH EH1 L OW0
> root@8932ca155955:~# echo "hello" | g2p-seq2seq --interactive --model data/models/cmudict 
cmudict/         cmudict-512/     cmudict-ipa-512/ 
root@8932ca155955:~# echo "hello" | g2p-seq2seq --interactive --model data/models/cmudict-512/
Loading vocabularies from data/models/cmudict-512/
Creating 2 layers of 512 units.
Reading model parameters from data/models/cmudict-512/
> H H
```

so there is something wrong with the 512 layer size model at this time.

If you want to try it out I have just uploaded these models [here](https://github.com/loretoparisi/docker/tree/master/g2p-seq2seq)
You can see that you have both the models data and dictionaries there for CMU and CMU2IPA.
Also, I'm currently training the CMU-IPA with 512 layer size, let's see what happens.

**Comment by loretoparisi** [comment]
@nurtas-m yes that was the issue, confirmed, in fact this is the error that I get after training from the CMU-IPA dictionary with the ordinary split:

```
~# echo "hello" | g2p-seq2seq --interactive --model data/models/cmudict-ipa-512/
Loading vocabularies from data/models/cmudict-ipa-512/
Creating 2 layers of 512 units.
Reading model parameters from data/models/cmudict-ipa-512/
> Traceback (most recent call last):
  File "/usr/local/bin/g2p-seq2seq", line 11, in <module>
    load_entry_point('g2p-seq2seq==5.0.0a0', 'console_scripts', 'g2p-seq2seq')()
  File "build/bdist.linux-x86_64/egg/g2p_seq2seq/app.py", line 105, in main
  File "build/bdist.linux-x86_64/egg/g2p_seq2seq/g2p.py", line 427, in interactive
UnicodeEncodeError: 'ascii' codec can't encode character u'\u025b' in position 2: ordinal not in range(128)
```

I'm going to change the split function and/or update the dictionary than.

**Comment by loretoparisi** [comment]
@nurtas-m Hello, I have prepared a new CMU vocabulary with IPA symbols spaced so like

```
abell	æ b e l
abella	æ b e l ə
abeln	æ b e l n
abelow	æ b e l əʊ
abels	æ b e l z
abelson	æ b e l s n
abend	æ b e n d
abend(1)	æ b e n d
abendroth	æ b e n d r əʊ θ
aber	æ b ə
abercrombie	æ b k r ɒ m ɪ
aberdeen	æ b ə d i: n
aberford	æ b ə f ə d
```

and I have tried a 64 node / layer first training:

```
Created model with fresh parameters.
Preparing G2P data
Loading vocabularies from data/models/cmudict-ipa-64
Reading development and training data.
Creating model with parameters:
Learning rate:        0.5
LR decay factor:      0.99
Max gradient norm:    5.0
Batch size:           64
Size of layer:        64
Number of layers:     2
Steps per checkpoint: 200
Max steps:            0
Optimizer:            sgd
Mode:                 g2p
```

while training I have got

```
Created model with fresh parameters.
global step 200 learning rate 0.5000 step-time 0.20 perplexity 2.91
  eval: perplexity 1.22
...
global step 33000 learning rate 0.3968 step-time 0.14 perplexity 1.00
  eval: perplexity 1.02
No improvement over last 17 times. Training will stop after -9iterations if no improvement was seen.
global step 33200 learning rate 0.3968 step-time 0.17 perplexity 1.00
  eval: perplexity 1.02
...
Loading vocabularies from data/models/cmudict-ipa-64
Creating 2 layers of 64 units.
Reading model parameters from data/models/cmudict-ipa-64
Symbols '5' are not in vocabulary
Words: 13330
Errors: 13318
WER: 0.999
Accuracy: 0.001
```

and by example for inference I have got encoding errors for words that have `unicode` like

```
root@8932ca155955:~# echo "aberdeeen" | g2p-seq2seq --interactive --model data/models/cmudict-ipa-64/
Loading vocabularies from data/models/cmudict-ipa-64/
Creating 2 layers of 64 units.
Reading model parameters from data/models/cmudict-ipa-64/
> Traceback (most recent call last):
  File "/usr/local/bin/g2p-seq2seq", line 11, in <module>
    load_entry_point('g2p-seq2seq==5.0.0a0', 'console_scripts', 'g2p-seq2seq')()
  File "build/bdist.linux-x86_64/egg/g2p_seq2seq/app.py", line 105, in main
  File "build/bdist.linux-x86_64/egg/g2p_seq2seq/g2p.py", line 427, in interactive
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe6' in position 0: ordinal not in range(128)
```

so I supposed I need also to handle unicode chars in the phonemes column like:

```
aberdeen	æ b ə d i: n
```

Thanks for your help!

**Comment by loretoparisi** [comment]
Closing this and opening a new issue specific for the encoding issues, thank you.
